version: 0.0
os: linux
files:
  - source: /
    destination: /srv/
permissions:
  - object: /srv/
    owner: "www-data"
    group: "www-data"
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 60
  AfterInstall:
    - location: scripts/after-install.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/application-start.sh
      timeout: 60
      runas: root
