#!/bin/bash

cd docker

COMPOSE="docker-compose exec -T "

echo
echo "==========================================="
echo "Running composer install..."
echo

$COMPOSE php composer install 2> /dev/null

if [ $? -eq 0 ]
then
  echo
  echo "Composer packages were updated successfully."
else
  echo
  echo "Updating Composer packages failed." >&2
  exit 1
fi

echo "==========================================="
echo
echo "==========================================="
echo "Running drush cache rebuild..."
echo

$COMPOSE php drush cr 2> /dev/null

if [ $? -eq 0 ]
then
  echo
  echo "Cache rebuilt successfully."
else
  echo
  echo "Rebuilding cache failed." >&2
  exit 1
fi

echo "==========================================="

exit 0